### ISSUE TITLE
Order of preprocessing scripts in README

### ISSUE THREAD

**Issue by DerWaldi** [sweetcocoa/pop2piano#4]
Hi Jongho,

Firstly, thank you for sharing your awesome work!

I am trying to get a deeper understanding of the preprocessing steps.

Is it possible, that "2. Estimate Pop's beats" and "3. synchronize midi" are swapped?
It seems that "pop_align.py" creates the pitch_shifted versions of the original tracks, which are required for the script "bpm_quantize.py".
So, I wonder if the order in the README is correct?

Thank you,
Sebastian

**Comment by sweetcocoa** [comment]
Thank you for opening this issue. and you are right, the order should be swapped.

Unfortunately, I don't have enough time to modify the repository these days. 

I will change the document ASAP.

thanks again.

FYI, the expected output structure of one sample would be like this:
```
├── -7lV0oJ0QXc                                                                                                                                                                                                                                             │   ├── EHl_eQhgefw.beatinterval.npy                                                                                                                                                                                                                        │   ├── EHl_eQhgefw.beatstep.npy
│   ├── EHl_eQhgefw.beattime.npy
│   ├── EHl_eQhgefw.mid
│   ├── EHl_eQhgefw.notes.npy
│   ├── EHl_eQhgefw.pitchshift.wav
│   ├── EHl_eQhgefw.qmidi.mid
│   ├── EHl_eQhgefw.qmix.flac
│   ├── EHl_eQhgefw.vocals.mp3
│   ├── EHl_eQhgefw.wav
│   └── The Beatles - With a Little Help from My Friends ____With A Little Help From My Friends - The Beatles _.txt
├── -7lV0oJ0QXc.mid
├── -7lV0oJ0QXc.wav
├── -7lV0oJ0QXc.yaml
```

and its meta file 

```
piano:
  uploader: Montechait
  title: The Beatles - With a Little Help from My Friends _ Piano Cover + Sheet Music
  ytid: -7lV0oJ0QXc
  duration: 172
  tuning_offset: 2
song:
  ytid: EHl_eQhgefw
  title: With A Little Help From My Friends - The Beatles _ 8D Audio with Lyrics
  duration: 164
  pitch_shift: 0
  tuning_offset: 5
tempo:
  bpm: 111.88993835449219
  confidence: 3.0150065422058105
eval:
  melody_chroma_accuracy: 0.5232774674115456
  melody_pitch_accuracy: 0.022139457893647838
```
